In [20]:
# Install scikit-learn if not installed
# !pip install scikit-learn

from sklearn.naive_bayes import MultinomialNB, ComplementNB, GaussianNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [2]:
# -----------------------------
# Example dataset (text data)
# -----------------------------
emails = [
    "win money now",       # spam
    "free money offer",    # spam
    "hello friend",        # not spam
    "meeting schedule",    # not spam
    "free win prize",      # spam
    "project report",      # not spam
]

labels = ["spam", "spam", "not_spam", "not_spam", "spam", "not_spam"]
"""Total samples = 6"""



In [21]:
# -----------------------------
# Convert text to count vectors
# -----------------------------
vectorizer = CountVectorizer()  #This creates a CountVectorizer object.
X = vectorizer.fit_transform(emails)   #fit_transform learns the vocabulary from emails and returns a sparse count matrix X or Converts emails into numeric count vectors.
y = labels    #CountVectorizer sorts them alphabetically.
"""Index mapping (very important):Word	Index
                                  free	0
                                  friend	1
                                  hello	  2
                                  meeting	3
                                  win    11

Each email becomes a vector of length 12.
Email 1: "win money now"

Contains: win money now

Vector:

[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1]
Because:

money → index 4

now → index 5

win → index 11
 Final matrix
 (6 rows, 12 columns)"""


'Index mapping (very important):Word\tIndex\n                                  free\t0\n                                  friend\t1\n                                  hello\t  2\n                                  meeting\t3\n                                  win    11\n\nEach email becomes a vector of length 12.\nEmail 1: "win money now"\n\nContains: win money now\n\nVector:\n\n[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1]\nBecause:\n\nmoney → index 4\n\nnow → index 5\n\nwin → index 11\n Final matrix \n (6 rows, 12 columns)'

X is NOT a normal NumPy array.

It is a:

Sparse matrix (specifically a scipy sparse matrix)

In [ ]:
print(vectorizer.vocabulary_)   # dict: token -> column index
print(X.shape)                  # (n_samples, n_features)
print(X.toarray())              # dense array view (small data only)

{'win': 11, 'money': 4, 'now': 5, 'free': 0, 'offer': 6, 'hello': 2, 'friend': 1, 'meeting': 3, 'schedule': 10, 'prize': 7, 'project': 8, 'report': 9}
(6, 12)
[[0 0 0 0 1 1 0 0 0 0 0 1]
 [1 0 0 0 1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 1 0 0]]


| Sparse Matrix               | Dense Array                  |
| --------------------------- | ---------------------------- |
| Stores only non-zero values | Stores every value           |
| Memory efficient            | Uses more memory             |
| Faster for large text data  | Slower for large sparse data |
| Used in NLP                 | Used in small datasets       |

Instead of storing:

[0 0 0 0 1 0 0 2]

It stores:

Index 4 → 1
Index 7 → 2

In [5]:

# # Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
# -----------------------------
# 1️ Multinomial Naive Bayes
# -----------------------------
mnb = MultinomialNB()  #creating an object of MultinomialNB.
mnb.fit(X_train, y_train)
y_pred_mnb = mnb.predict(X_test)
print("Multinomial NB Accuracy:", accuracy_score(y_test, y_pred_mnb))




Multinomial NB Accuracy: 1.0


In [6]:
import numpy as np


In [8]:
print("classes:", mnb.classes_)
print("class_count_:", mnb.class_count_)
print("feature_count_ shape:", mnb.feature_count_.shape)  # (n_classes, n_features)
print("feature_log_prob_:", np.exp(mnb.feature_log_prob_)) # back to probability space


classes: ['not_spam' 'spam']
class_count_: [3. 1.]
feature_count_ shape: (2, 12)
feature_log_prob_: [[0.05555556 0.11111111 0.11111111 0.11111111 0.05555556 0.05555556
  0.05555556 0.05555556 0.11111111 0.11111111 0.11111111 0.05555556]
 [0.13333333 0.06666667 0.06666667 0.06666667 0.06666667 0.06666667
  0.06666667 0.13333333 0.06666667 0.06666667 0.06666667 0.13333333]]


In [ ]:
# [[0.05555556 0.11111111 0.11111111 0.11111111 0.05555556 0.05555556
#   0.05555556 0.05555556 0.11111111 0.11111111 0.11111111 0.05555556]    # Not spam
#  [0.13333333 0.06666667 0.06666667 0.06666667 0.06666667 0.06666667
#   0.06666667 0.13333333 0.06666667 0.06666667 0.06666667 0.13333333]]   # spam

In [9]:
y_pred_mnb = mnb.predict(X_test)
print(y_pred_mnb)   # shows predicted classes for each email


['spam' 'spam']


In [11]:
probs = mnb.predict_proba(X_test)
print(probs)
# Output : Sample 1 (Not spam, spam), sample 2 (Not Spam, spam)

[[0.46468401 0.53531599]
 [0.46468401 0.53531599]]


In [12]:
# -----------------------------
# 2️ Complement Naive Bayes
# -----------------------------
cnb = ComplementNB()
cnb.fit(X_train, y_train)
y_pred_cnb = cnb.predict(X_test)
print("Complement NB Accuracy:", accuracy_score(y_test, y_pred_cnb))



Complement NB Accuracy: 1.0


In [13]:
print("cnb.classes_:", cnb.classes_)
print("cnb.class_count_:", cnb.class_count_)
print("cnb.feature_count_.shape:", cnb.feature_count_.shape)
print("cnb.feature_log_prob_ (exp->prob):", np.exp(cnb.feature_log_prob_))

cnb.classes_: ['not_spam' 'spam']
cnb.class_count_: [3. 1.]
cnb.feature_count_.shape: (2, 12)
cnb.feature_log_prob_ (exp->prob): [[ 7.5 15.  15.  15.  15.  15.  15.   7.5 15.  15.  15.   7.5]
 [18.   9.   9.   9.  18.  18.  18.  18.   9.   9.   9.  18. ]]


In [ ]:
# cnb.feature_log_prob_ (exp->prob): [[ 7.5 15.  15.  15.  15.  15.  15.   7.5 15.  15.  15.   7.5]   # Not sapm
#  [18.   9.   9.   9.  18.  18.  18.  18.   9.   9.   9.  18. ]]  # spam

#Complement-based weights derived from log probabilities, are NOT frequencies.

#They are also NOT normal probabilities.
#This reflects how common each word is in not_spam.


"""Let’s simplify:

Suppose for the "spam" row:

Word A = 18

Word B = 9

That means:

Word A appears more in the complement (not_spam) than Word B.

So Word A is less useful for spam
because it’s common in not_spam."""

In [ ]:
y_pred_cnb = cnb.predict(X_test)
print(y_pred_cnb)   # shows predicted classes for each email


['spam' 'spam']


In [14]:
# -----------------------------
# 3️ Gaussian Naive Bayes
# -----------------------------
# For GaussianNB, we need dense numeric features
# Let's create a simple numeric dataset
import numpy as np

# Features: height (cm), weight (kg)
X_numeric = np.array([
    [180, 75],  # tall
    [175, 70],  # tall
    [160, 60],  # short
    [165, 65],  # short
    [178, 72],  # tall
    [155, 55],  # short
])
y_numeric = ["tall", "tall", "short", "short", "tall", "short"]

gnb = GaussianNB()
gnb.fit(X_numeric, y_numeric)
y_pred_gnb = gnb.predict([[170, 68], [162, 58]])  # New examples
print("Gaussian NB Predictions:", y_pred_gnb)

Gaussian NB Predictions: ['short' 'short']


In [15]:
print("gnb.classes_:", gnb.classes_)

gnb.classes_: ['short' 'tall']


In [ ]:
print("Class means (theta_):", gnb.theta_)
print("Class variances (var_):", gnb.var_)
print("Class priors:", gnb.class_prior_)

 #scikit-learn sorts class labels alphabetically.
"""theta_ → where the class center is
var_ → how wide the class spread is
class_prior_ → how common the class is"""

"""This means:

For short people:

Average height = 160 cm

Average weight = 60 kg

For tall people:

Average height ≈ 177.67 cm

Average weight ≈ 72.33 kg

So theta_ = mean (μ) of each feature per class."""

"""Interpretation:

Short group is more spread out.
Tall group is more tightly clustered.

Smaller variance → data points are closer to the mean."""



"""This means:

P(short) = 0.5

P(tall) = 0.5

Because you had:

3 short

3 tall

Equal counts → equal prior probability."""

Class means (theta_): [[160.          60.        ]
 [177.66666667  72.33333333]]
Class variances (var_): [[16.66666676 16.66666676]
 [ 4.22222231  4.22222231]]
Class priors: [0.5 0.5]


In [ ]:
# Row 0 → 'short' class

# Row 1 → 'tall' class

In [16]:
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.feature_extraction.text import CountVectorizer

# -----------------------------
# Extreme imbalanced dataset
# -----------------------------
emails = [
    "free win money",        # Spam
    "free money offer",      # Spam
    "hello friend free",     # Not-Spam
    "meeting schedule free", # Not-Spam
    "project report daily",  # Not-Spam
    "team update work",      # Not-Spam
    "work task report",      # Not-Spam
    "daily report hello",    # Not-Spam
]

labels = ["spam","spam","not_spam","not_spam","not_spam","not_spam","not_spam","not_spam"]

new_email = ["free"]


# -----------------------------
# Convert text to count vectors
# -----------------------------
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)
X_new = vectorizer.transform(new_email)
y = labels


In [17]:
mnb = MultinomialNB()
mnb.fit(X, y)
pred_mnb = mnb.predict(X_new)
print("Multinomial NB Prediction:", pred_mnb)
print("Multinomial NB Probabilities:", mnb.predict_proba(X_new))

Multinomial NB Prediction: ['not_spam']
Multinomial NB Probabilities: [[0.65625 0.34375]]


In [18]:
cnb = ComplementNB()
cnb.fit(X, y)
pred_cnb = cnb.predict(X_new)
print("Complement NB Prediction:", pred_cnb)
print("Complement NB Probabilities:", cnb.predict_proba(X_new))

Complement NB Prediction: ['spam']
Complement NB Probabilities: [[0.38888889 0.61111111]]


In [19]:
print("Multinomial NB Probabilities:", mnb.predict_proba(X_new))
print("Complement NB Probabilities:", cnb.predict_proba(X_new))

Multinomial NB Probabilities: [[0.65625 0.34375]]
Complement NB Probabilities: [[0.38888889 0.61111111]]
